### ISSUE TITLE
offset & limit parameters is required for some function

### ISSUE THREAD

**Issue by bkhezry** [ganjoor/GanjoorAPI-Swift#1]
for `poets`, `poems`, `topCategories` and `categories `functions maybe offset & limit parameter is required.

**Comment by euwars** [comment]
I think having standard offset is more consistent than asking for limit, so for `poets` and `categories` now do have offset with the default limit of `50`. 
`topCategories` is always limited to 6.
keep in mind you always should pass the offset value as Int for those two methods.
267f6f3443f62760a4eeb4bf5811a82dbf1777a6 ded96c688ea3813f65994cb175d7bd86b6156fa0
